/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algebrablocks;

import javax.swing.JPanel;

// you need to specify the classpath when you compile because this is from a downloaded library. the classpath should lead to the .jar file you downloaded
// source: http://commons.apache.org/proper/commons-math/download_math.cgi
import org.apache.commons.math3.fraction.Fraction;

/**
 *
 * @author Jorg3
 */
public class Block extends JPanel
{
    /**
     * Creates new form Block
     */
    //Variables   
    private boolean isLHS;
	private Fraction num;
	private String coeff;

    protected int initialX;
    protected int initialY;
   
    public Block(boolean IsLeftHandSide, Fraction Number) throws IllegalArgumentException
	{
		if (Number == null) { throw new IllegalArgumentException(); }
        initComponents();
		isLHS = IsLeftHandSide;
		num = Number;
		coeff = "";
    }
    public Block(boolean IsLeftHandSide, Fraction Number, String Coefficient) throws IllegalArgumentException
	{
		if (Coefficient == null || Number == null) { throw new IllegalArgumentException(); }
        initComponents();
		isLHS = IsLeftHandSide;
		num = Number;
		coeff = Coefficient;
    }
	public Block(Block blk)
	{
		initComponents();
		isLHS = blk.isLHS();
		num = blk.Number();
		coeff = blk.Coefficient();
	}

    //Methods...
    public void FlipSide() { isLHS = !isLHS; }
    public boolean isLHS() { return isLHS; }

	public Fraction Number() { return num; }
	public String Coefficient() { return coeff; }
    
	public void Number(Fraction Number) { num = Number; }
	public void Coefficient(String Coefficient) { coeff = Coefficient; }

	public int getInitialX() { return initialX; }
    public int getInitialY() { return initialY; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

	public Block Split()
	{
		return new Block(true, new Fraction(0));
	}

	public static Block Merge(Block lhs, Block rhs) throws Exception
	{
		if (lhs.Coefficient() != rhs.Coefficient())
		{
			throw new ArithmeticException("Cannot combine unlike terms");
		}
		if (lhs.isLHS() != rhs.isLHS())
		{
			throw new IllegalArgumentException("Can only merge blocks on the same side");
		}
		return Block.Add(lhs, rhs);
	}

	private static Block Add(Block lhs, Block rhs)
	{
		return new Block(lhs.isLHS(), Fraction.Add(lhs.Number(), rhs.Number()),
				lhs.Coefficient());
	}
	public void Multiply(Block other) { }

	public String toString()
	{
		return num.toString() + coeff;
	}
}
